# Sunucu Portu
server.port=8080

# PostgreSQL Veritabanı Bağlantı Ayarları
spring.datasource.url=jdbc:postgresql://localhost:5432/voltifydb
spring.datasource.username=voltify_user
spring.datasource.password=voltify_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate (JPA) Ayarları - Tabloları otomatik oluşturması için[cite: 1]
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect